title: "Solidarity will win!"
url: https://solidarityhh.github.io/

# I18N
languages: ["en", "de", "fa"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

plugins:
  - jekyll-polyglot
